package org.alpen.musiklopedia.entity;
// Generated Jun 21, 2015 10:43:06 PM by Hibernate Tools 4.3.1

import java.util.Objects;




/**
 * Album generated by hbm2java
 */
public class Album  implements java.io.Serializable {


     private Integer id;
     private String namaalbum;
     private String namaband;
     private String pencipta;
     private String tahun;

    public Album() {
    }

    public Album(String namaalbum, String namaband, String pencipta, String tahun) {
       this.namaalbum = namaalbum;
       this.namaband = namaband;
       this.pencipta = pencipta;
       this.tahun = tahun;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNamaalbum() {
        return this.namaalbum;
    }
    
    public void setNamaalbum(String namaalbum) {
        this.namaalbum = namaalbum;
    }
    public String getNamaband() {
        return this.namaband;
    }
    
    public void setNamaband(String namaband) {
        this.namaband = namaband;
    }
    public String getPencipta() {
        return this.pencipta;
    }
    
    public void setPencipta(String pencipta) {
        this.pencipta = pencipta;
    }
    public String getTahun() {
        return this.tahun;
    }
    
    public void setTahun(String tahun) {
        this.tahun = tahun;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 23 * hash + this.id;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Album other = (Album) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }


}


